# примеры API-запросов

# создание продукта
POST http://localhost:8000/api/v1/products/
Content-Type: application/json

{
  "title": "Помидор",
  "description": "Лучшие помидоры на рынке"
}

###

# получение продуктов
GET http://localhost:8000/api/v1/products/
Content-Type: application/json

###

# обновление продукта
PATCH http://localhost:8000/api/v1/products/1/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE http://localhost:8000/api/v1/products/5
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET http://localhost:8000/api/v1/products/?search=баклажан
Content-Type: application/json

###

# создание склада
POST http://localhost:8000/api/v1/stocks/
Content-Type: application/json

{
  "address": "Ленина, 1",
  "positions": [
    {
      "product": 1,
      "quantity": 210,
      "price": 139.50
    },
    {
      "product": 4,
      "quantity": 155,
      "price": 171.80
    },
    {
      "product": 3,
      "quantity": 56,
      "price": 150.50
    }
  ]
}

###

# обновляем записи на складе
PATCH http://localhost:8000/api/v1/stocks/15/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 140,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET http://localhost:8000/api/v1/stocks/?products=бак
Content-Type: application/json
